### ISSUE TITLE
OSCommerce HTML not properly parsed

### ISSUE THREAD

**Issue by westonbelk** [CUCyber/scoreboard#1]
Service: OSCommerce 2.2-MS1
```
HTTP: trying 10.0.130.5:80 for GET /catalog/default.php
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/scoreboard-0.0.1-py3.4.egg/scoreboard/poll.py", line 93, in watch
    if check(opt):
  File "/usr/lib/python3.4/site-packages/scoreboard-0.0.1-py3.4.egg/scoreboard/poll.py", line 35, in check
    return scoreboard.http.check(**opt)
  File "/usr/lib/python3.4/site-packages/scoreboard-0.0.1-py3.4.egg/scoreboard/http.py", line 37, in check
    up = up and re.search(regex, httpc.getresponse().read().decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 24197: invalid continuation byte
```

**Comment by lilyinstarlight** [comment]
Since OSCommerce seems to give an invalid UTF-8 character, you can use a `bytes` regex like `{'regex': b'<html>'}`.
